version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/python:3.7.9

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install --upgrade pip

jobs:
  test_lasso_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Runnning ML model tests
          command: |
            python3 -m pip install -r packages/lasso/requirements.txt
            export PYTHONPATH=$PYTHONPATH:'./packages/lasso'
            pytest -s packages/lasso/tests

  test_ml_api:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: 
            deps-py-{{ checksum "packages/ml-app/requirements.txt" }}
      - *prepare_venv
      - run:
          name: Running API tests
          command: |
            python3 -m pip install -r packages/ml-app/requirements.txt
            export PYTHONPATH=$PYTHONPATH:'./packages/ml-app'
            pytest -s packages/ml-app/tests
      - save_cache:
          paths:
            - "venv/"
          key: 
            deps-py-{{ checksum "packages/ml-app/requirements.txt" }}

  train_and_publish_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Train model
          command: |
            python3 -m pip install -r packages/lasso/requirements.txt
            PYTHONPATH='./packages/lasso' python3 packages/lasso/lasso/train.py
      - run:
          name: Publish model
          command: |
            ./scripts/publish_model.sh packages/lasso

workflows:
  version: 2
  test-all:
    jobs:
      - test_lasso_model
      - test_ml_api
      - train_and_publish_model
      - test_ml_api:
          requires:
            - train_and_publish_model
