version: 2

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

jobs:
  test_lasso_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Runnning ML model tests
          command: |
            pip install -r packages/lasso/requirements.txt
            export PYTHONPATH=$PYTHONPATH:'./packages/lasso'
            pytest -s packages/lasso/tests

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Running API tests
          command: |
            pip install -r packages/ml-app/requirements.txt
            export PYTHONPATH=$PYTHONPATH:'./packages/ml-app/api'
            pytest -s packages/ml-app/tests

  train_and_publish_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Running train and publish model
          command: |
            pip install -r packages/lasso/requirements.txt
            ./scripts/publish_model.sh packages/lasso/setup.py

workflows:
  version: 2
  test-all:
    jobs:
      - test_lasso_model
      - test_ml_api
      - train_and_publish_model
      - test_ml_api:
          requires:
            - train_and_publish_model
