version: 2
jobs:
  test_lasso_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Runnning ML model tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/lasso/requirements.txt
            export PYTHONPATH=$PYTHONPATH:'./packages/lasso'
            py.test -vv packages/lasso/tests

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Running API tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml-app/requirements.txt
            pytest packages/ml-app/tests

  train_and_publish_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Running train and publish model
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/lasso/requirements.txt
            ./scripts/publish_model.sh packages/lasso/setup.py

workflows:
  version: 2
  test-all:
    jobs:
      - test_lasso_model
