version: 2
jobs:
  test_lasso_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/lasso/requirements.txt
            # chmod +x ./scripts/fetch_kaggle_dataset.sh
            # ./scripts/fetch_kaggle_dataset.sh
            py.test -vv packages/lasso/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_lasso_model
